### ISSUE TITLE
StreamGraphs are available in Altair

### ISSUE THREAD

**Issue by dhirschfeld** [holtzy/The-Python-Graph-Gallery#1]
Not sure if you're aware of Altair, but it *does* have a streamgraph implementation available:

https://altair-viz.github.io/gallery/stacked_area_stream.html

**Comment by dhirschfeld** [comment]
In case you're interested, I found the below blog post interesting:
https://twitter.com/vlandham/status/977237921005633536

**Comment by holtzy** [comment]
I've added a link to the altair stream graph example in the new version of the gallery.
