### ISSUE TITLE
Contributing a stacked area chart example to the python-graph-gallery

### ISSUE THREAD

**Issue by alcazar90** [holtzy/The-Python-Graph-Gallery#115]
Hi

Preparing the content for a talk I gave in data visualization with python, I reproduced the stack area chart from an article published by The New York Times: ["How Severe Is the Western Drought? See For Yourself."](https://www.nytimes.com/interactive/2021/06/11/climate/california-western-drought-map.html)

![](https://github.com/alcazar90/WomenInData-Guatemala2021/blob/master/img/us_drought_replica_NYT.png?raw=true)

To contribute to the gallery, I need to write a blog post like the following? https://www.python-graph-gallery.com/web-ggbetweenstats-with-matplotlib

best,
Cristóbal

**Comment by holtzy** [comment]
Hi @alcazar90 ,

Pinging you a last time as I am very interested in listing this chart in the gallery! Best,
