### ISSUE TITLE
Alternate Design forms: Weighted Graphs for Correlation Networks

### ISSUE THREAD

**Issue by BradKML** [holtzy/The-Python-Graph-Gallery#118]
Observing https://github.com/holtzy/The-Python-Graph-Gallery/blob/master/src/notebooks/327-network-from-correlation-matrix.ipynb
With reference to https://github.com/WestHealth/pyvis/issues/123 and
- https://stackoverflow.com/a/12374265
- https://www.r-graph-gallery.com/250-correlation-network-with-igraph.html
- https://psych-networks.com/r-tutorial-identify-communities-items-networks/

Instead of using thresholds, is it possible to simply weight the connections between 0 and infinity?

https://towardsdatascience.com/eveything-you-need-to-know-about-interpreting-correlations-2c485841c0b8

On this page, anything under 0.3 makes negligible correlation, and anything over 0.9 is clearly correlated, with 0.6 being the middle of correlation significance. Possibly, for scaling purposes (where 0 correlation leads to 0 weight, and 0.6 correlation leads to 1, 1 correlated to b^0.583):

```
from numpy import tanh, exp
def scale(x):
    return exp(tanh((x-0.6)/0.6))
```

**Comment by BrandonKMLee** [comment]
They rely on weights to do the job spectral clustering seems to work.
https://networkx.org/documentation/stable/reference/generated/networkx.drawing.layout.spectral_layout.html

**Comment by holtzy** [comment]
Hi!
Thanks a lot for the feedback!
I think this is a bit too specific/niche for the gallery. We are just here to give some simple & educational graph examples!
