### ISSUE TITLE
Histogram is not exclusive to numeric variables

### ISSUE THREAD

**Issue by benjaminbauer** [holtzy/The-Python-Graph-Gallery#119]
https://github.com/holtzy/The-Python-Graph-Gallery/blob/60bae35a8876f33b0854b76741e63463bda7ab42/src/pages/histogram.js#L17

> A Histogram represents the distribution of a **numeric** variable

Histograms are commonly used for any kind of variable including non-numeric, i.e. categorical variables.

**Comment by holtzy** [comment]
Hi Benjamin,

Can you show me an example of a histogram made for categorical variables? 🤔

Are you sure you are not thinking about a barplot?

Thanks for your feedback!
