### ISSUE TITLE
Missing file bike.csv

### ISSUE THREAD

**Issue by giacomodelbianco** [holtzy/The-Python-Graph-Gallery#129]
I was trying to make the time-serie graph reported on the site:

https://r-graph-gallery.com/318-custom-dygraphs-time-series-example.html

Which loads the following dataframe:
https://python-graph-gallery.com/wp-content/uploads/bike.csv

But I realized the dataframe **bike.csv** is not longer present in your site. Is it possible to restore?

**Comment by holtzy** [comment]
I do not have access to this file anymore :(
