### ISSUE TITLE
Beautiful circos plots in matplotlib

### ISSUE THREAD

**Issue by ponnhide** [holtzy/The-Python-Graph-Gallery#133]
Hi, please let me promote my developing library.

You mentioned, "The most common library like Matplotlib and Seaborn will not be of any help to build one." on your website.
However, I manage and develop [pyCircos](https://github.com/ponnhide/pyCircos) that allow drawing circos plots (chord diagrams). 
The library is implemented based on matplotlib, so the drawn object can be customized in a general matplotlib manner. 
The following example plot is generated by using pyCircos. 
![download](https://user-images.githubusercontent.com/2762763/164152855-449a2892-ddfd-430f-8378-3583e84d2273.png)

If you are interested in pyCircos, please try to execute the example code on [Google colab](https://colab.research.google.com/drive/1xmAnv7AHWUTA2HWfjqV1lFWkFMSLJHG0?usp=sharing).
I would like to be glad if you could introduce pyCircos on your website.

**Comment by holtzy** [comment]
@JosephBARBIERDARNAL to investigate!

**Comment by JosephBARBIERDARNAL** [comment]
Hi @ponnhide ! this looks pretty good!

Have you consider developing a slightly more intuitive API? For example, this code:

```
#heatmap
values_all   = [] 
arcdata_dict = collections.defaultdict(dict)
with open("pycircos/sample_data/example_data_rect_gradual.csv") as f:
    f.readline()
    for line in f:
        line  = line.rstrip().split(",")
        name  = line[0]     
        start = int(line[1])-1
        end   = int(line[2]) 
        width = end-start 
        if name not in arcdata_dict:
            arcdata_dict[name]["positions"] = []
            arcdata_dict[name]["widths"]    = [] 
            arcdata_dict[name]["values"]    = [] 
        arcdata_dict[name]["positions"].append(start) 
        arcdata_dict[name]["widths"].append(width)
        arcdata_dict[name]["values"].append(float(line[-1]))
        values_all.append(float(line[-1]))

vmin, vmax = min(values_all), max(values_all) 
for key in arcdata_dict:
    circle.heatmap(key, data=arcdata_dict[key]["values"], positions=arcdata_dict[key]["positions"], 
                   width=arcdata_dict[key]["widths"], raxis_range=[630,670], vmin=vmin, vmax=vmax, 
                   cmap=plt.cm.viridis)
```

I believe it can easily be wrapped around a function with a few arguments since every user will use it the same way. Is that something you have thought about?
