### ISSUE TITLE
FiveThirtyEight spelled incorrectly as FiveThirtyHeight

### ISSUE THREAD

**Issue by Fnlc9IeLOO** [holtzy/The-Python-Graph-Gallery#134]
On this page [https://www.python-graph-gallery.com/199-matplotlib-style-sheets](https://www.python-graph-gallery.com/199-matplotlib-style-sheets) the spelling of FiveThirtyEight is incorrect in two locations and includes an H by mistake. However, It is correct in the places that matter such as the link to their website and in the code example. I included a screenshot below.

![Screen Shot 2022-05-16 at 10 39 13](https://user-images.githubusercontent.com/56223519/168618914-1d221cc3-d068-43f5-b318-797969016457.png)

**Comment by holtzy** [comment]
Fixed! Thanks a lot
