### ISSUE TITLE
Incorrect Title For Seaborn Ridgeline Example Code Page

### ISSUE THREAD

**Issue by PaulWGraham** [holtzy/The-Python-Graph-Gallery#135]
The title of

[https://www.python-graph-gallery.com/ridgeline-graph-seaborn](https://www.python-graph-gallery.com/ridgeline-graph-seaborn)

reads **"Drawing a ridgeline graph with Plotly"**

but it is a Seaborn example and should probably read **"Drawing a ridgeline graph with Seaborn"**

**Comment by holtzy** [comment]
Thanks! Just fixed it;
