### ISSUE TITLE
Changing the grid size after creating an axis

### ISSUE THREAD

**Issue by RomanCLV** [holtzy/The-Python-Graph-Gallery#139]
Hello,
I just started using Pyplot and I read this article (https://www.python-graph-gallery.com/194-split-the-graphic-window-with-subplot) about axis placement.
If I create a 2x2 graph with two axes, like this:
`
plt.subplot(221)
`
`
plt.subplot(223)
`

I am wondering how can i change from 2x2 to 2x1, in a second time (for instance, an event's callback),
to have  something like this: 

So I start with this:

 'o' are axis ; '_' are empty space
 __ 
| o _ |  
| o _ |   

 ... do some actions ...

 and I finish with this:
 __
| o | 
| o | 

Thanks for your time :)

**Comment by JosephBARBIERDARNAL** [comment]
I @RomanCLV ! As far as I know, what you're looking for is the clf() function (clear figure), which is unfortunately poorly described [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.clf.html)
