### ISSUE TITLE
Python sankey options

### ISSUE THREAD

**Issue by Cimbali** [holtzy/The-Python-Graph-Gallery#14]
Hi and thanks for the very useful resource.

I think you’re a little short on sankey options, there’s only matplotlib which is a little basic/ugly. Could consider adding maybe [pySankey](https://github.com/anazalea/pySankey) ?

I don’t know if there are other decent options, there’s [floweaver](https://github.com/ricklupton/floweaver) (previously pysankeyview), but it apparently requires other packages such as `ipansankeywidget` to be displayed.

**Comment by holtzy** [comment]
Good point; I'm gonna add a plotly example I think. Thanks!

**Comment by holtzy** [comment]
I've added an example with plotly
pySankey will follow
