### ISSUE TITLE
sns.kdeplot deprecated keyword: vertical 

### ISSUE THREAD

**Issue by gregwhammond** [holtzy/The-Python-Graph-Gallery#155]
On https://www.python-graph-gallery.com/72-horizontal-density-plot

`sns.kdeplot(df['sepal_width'],  shade=True, vertical=True, color="skyblue")`
warns `vertical` keyword deprecated. 

`y` keyword appears to fix that,
`sns.kdeplot(y=df['sepal_width'],  shade=True, color="skyblue")`

**Comment by JosephBARBIERDARNAL** [comment]
Hi! This will be fixed with #288

**Comment by holtzy** [comment]
Thanks to you both!
