### ISSUE TITLE
Change distplot() function with displot()

### ISSUE THREAD

**Issue by dipesh-chatrola** [holtzy/The-Python-Graph-Gallery#157]
![1](https://user-images.githubusercontent.com/87219133/210488436-9321772b-a48d-44f3-b716-27ebc1b5290a.jpg)
![2](https://user-images.githubusercontent.com/87219133/210488489-c1031671-c608-4465-8f8a-7debbe069eee.jpg)
`distplot` is a deprecated function and will be removed in seaborn v0.14.0. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).

**Comment by holtzy** [comment]
Thanks @dipesh-chatrola for the feedback! 🙏🙏
