### ISSUE TITLE
Missleading/Incorrect circular bar heights in case of the lower limit exciding the maximum value

### ISSUE THREAD

**Issue by matz2532** [holtzy/The-Python-Graph-Gallery#165]
In [circular-barplot-basic](https://www.python-graph-gallery.com/circular-barplot-basic) the bar plot heights can become unexpected and wrong, when the lower limit is higher than the maximum value. 
```
import numpy as np
def convertValueToBarHeight(values, lowerLimit):
    max = np.max(values)
    slope = (max - lowerLimit) / max
    heights = slope * values + lowerLimit
    return heights

values=np.array([0.0063,0.0079])
print(convertValueToBarHeight(values, 30))
print(convertValueToBarHeight(values, 0.0079))
print(convertValueToBarHeight(values, 0))
[6.0822 0.0079]
[0.0079 0.0079]
[0.0063 0.0079]
```
I would suggest just adding an assert or warning in the code.
I hope it will help others avoid the same pitfall.

**Comment by holtzy** [comment]
Thanks for the feedback.
I think it is not too bad to have exceptions like that sometimes. My examples are mainly for educative purpose, so the general idea is still conveyed!
