### ISSUE TITLE
Small error: It's should be its

### ISSUE THREAD

**Issue by Bass2015** [holtzy/The-Python-Graph-Gallery#169]
First of all, thanks for your amazing website! It's being very useful. 
I spotted a very tiny error in this page:
https://www.python-graph-gallery.com/circular-packing-several-levels-of-hierarchy

Where you say "It's `circlify()` function ...", should say "**Its** `circlify()` function...", withouht the apostrophe, as here it is used as a possessive pronoun. 
![image](https://user-images.githubusercontent.com/78235553/235107443-79ea2172-bf55-47d4-b92b-7b8852983f6b.png)

Well, thanks again!

**Comment by holtzy** [comment]
Thanks, fixed!
