### ISSUE TITLE
Fix Favicon

### ISSUE THREAD

**Issue by holtzy** [holtzy/The-Python-Graph-Gallery#205]

**Comment by Kratos9211** [comment]
Hey,I can help you with this issue but could give me the proper location of the html file. Can't really find it on the codebase but on the browser inspect. I can view the HTML written as index inside the static folder but when I viewed inside the static folder there was no such thing .

**Comment by holtzy** [comment]
Fixed by itself 🤔

![image](https://github.com/holtzy/The-Python-Graph-Gallery/assets/10254401/41c91e7e-4605-46fa-b32d-3149819301e5)
