### ISSUE TITLE
Hierarchical Edge Bundling in Python

### ISSUE THREAD

**Issue by XiyuanWu** [holtzy/The-Python-Graph-Gallery#280]
I think it's possible to use Python to draw Hierarchical Edge Bundling. I have an example small chip of code: 
```
def graph_chart():

    c.add(
        "",
        categories=category,
        nodes=nodes_list,
        links=links_list,
        layout="circular",
        is_rotate_label=True,
        linestyle_opts=opts.LineStyleOpts(color="source", curve=0.3)
            )
    c.set_global_opts(
        legend_opts=opts.LegendOpts(orient="vertical", pos_left="3%", pos_top="20%"),
        title_opts=opts.TitleOpts(title="星级推荐")
    )
    return c
```
Sample output: 
<img width="679" alt="image" src="https://github.com/holtzy/The-Python-Graph-Gallery/assets/149738743/d06fdc75-9c39-46e5-a571-a44f30e2a672">
Please ignore the non-english languages. 
 I think this is a simple version for Hierarchical Edge Bundling. complete code in my repositories.

**Comment by XiyuanWu** [comment]
The complete link is in [here](https://github.com/XiyuanWu/Application_of_Python/tree/main/Data_Visualization).

This whole project was about combining different kinds of graphs into an interactive dashboard, index.html file was also uploaded.

**Comment by JosephBARBIERDARNAL** [comment]
Hi @XiyuanWu !
I've had a look at the library you're using, and although it seems possible to make very nice graphs, the library's non-English documentation makes it IMO too complex to use and add to the gallery

@holtzy what do you think?

**Comment by XiyuanWu** [comment]
Hi, 

I found this English Documentation [Here](https://gallery.pyecharts.org/#/README_EN)
In left columns, find Graph
![image](https://github.com/holtzy/The-Python-Graph-Gallery/assets/149738743/6db65469-7920-47cd-8867-25d7ae189ab2)
There are 6 types of relationship graphs, and the last one is what we are talking about right now. 

example:
![image](https://github.com/holtzy/The-Python-Graph-Gallery/assets/149738743/5e610d95-9f2a-4076-9adb-73b53270c496)
link: [here](https://gallery.pyecharts.org/#/Graph/graph_les_miserables)

**Comment by XiyuanWu** [comment]
And their GitHub page: [here](https://github.com/pyecharts/pyecharts)
