### ISSUE TITLE
footer does not appear completly

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [holtzy/The-Python-Graph-Gallery#295]
In my browser, the subscribe section does not appear well and need to scroll @holtzy 

<img width="909" alt="Screenshot 2024-03-07 at 11 19 46" src="https://github.com/holtzy/The-Python-Graph-Gallery/assets/79746670/c6f5dbed-6bc8-4a3b-8744-da8ef6c0ad85">

**Comment by holtzy** [comment]
Kind of fixed but I do not have a proper way to do it
