### ISSUE TITLE
improve wordcloud section

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [holtzy/The-Python-Graph-Gallery#367]
- the https://python-graph-gallery.com/wordcloud/ section lacks good examples and overall style

- plus, python has a wordcloud package with 10k github stars with nice features https://github.com/amueller/word_cloud

- current images look bad:

<img width="867" alt="Screenshot 2024-04-05 at 09 53 44" src="https://github.com/holtzy/The-Python-Graph-Gallery/assets/79746670/7394056d-16d0-4cf7-bc7f-495882178583">

**Comment by JosephBARBIERDARNAL** [comment]
fixed with #368

**Comment by holtzy** [comment]
Noicie!
