### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by Zemerik** [holtzy/The-Python-Graph-Gallery#381]
Currently the website looks a bit blank and doesn't stand out when someone looks at it for the first time due to the plain white background. Adding a custom image or changing the color from white to maybe blue can make the website look extremely attractive.

**Comment by holtzy** [comment]
Hi @Zemerik 

Thanks for the feedback!
To be honest I really like the current design. But I'm always interested in alternative designs. Do you have a figma prototype?

Cheers,

Yan

**Comment by Zemerik** [comment]
Hey @holtzy , 

Thanks for replying!
Unfortunately I don't have a figma prototype, however what I will suggest is to add a dark theme to the website. 

Regards, 
Zemerik
