### ISSUE TITLE
button for copy code

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [holtzy/The-Python-Graph-Gallery#384]
I think it would be a nice feature to be able to just click on a button to copy code, like in following example:

<img width="829" alt="Screenshot 2024-04-19 at 11 02 54" src="https://github.com/holtzy/The-Python-Graph-Gallery/assets/79746670/a2a9272d-6992-40ec-b86d-ec6d5e3db3db">

**Comment by JosephBARBIERDARNAL** [comment]
i've already done it once in the past, do you want me to carry it?

**Comment by holtzy** [comment]
Very good Idea but I think I will do it.
