### ISSUE TITLE
aquarel lib for easy styling in matplotlib

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [holtzy/The-Python-Graph-Gallery#386]
https://github.com/lgienapp/aquarel

**Comment by JosephBARBIERDARNAL** [comment]
other lib with theme: https://medium.com/@alexroz/matplotlib-makeover-6-python-styling-libraries-for-amazing-plots-5152f16992f5

**Comment by holtzy** [comment]
Keep the list growing this is gonna be useful!
