### ISSUE TITLE
Basemap deprecated in favor of cartopy

### ISSUE THREAD

**Issue by nelerey** [holtzy/The-Python-Graph-Gallery#57]
The maps section still has a basemap subtitle in it, however basemap has been deprecated. Do you plan on replacing this with cartopy? 
See https://scitools.org.uk/cartopy/docs/latest/ for more on the cartopy project and https://matplotlib.org/basemap/ for the basemap deprecation notice.

**Comment by holtzy** [comment]
Thanks for the feedback, that's definitely something I should correct
