### ISSUE TITLE
Link in STREAMCHART page broken

### ISSUE THREAD

**Issue by malbasi** [holtzy/The-Python-Graph-Gallery#6]
The link that leads to

Under the "Altair" heading, there is a link to the code "for the adjacent figure." That link returns a 404. Here is the broken link:
https://altair-viz.github.io/gallery/stacked_area_stream.html

I believe the link should point to the following page instead:
https://altair-viz.github.io/gallery/streamgraph.html

**Comment by holtzy** [comment]
Corrected,
Thanks very much!
