### ISSUE TITLE
wrong links for grouped/stacked barplot

### ISSUE THREAD

**Issue by holtzy** [holtzy/The-Python-Graph-Gallery#62]
Hello Mr. Holtz,

I just wanted to notify you (in case you did not know) that there is an error in the links found in the section 'Stacked and Grouped barplot with Matplotlib' in https://www.python-graph-gallery.com/barplot/. 

So the error is that if you click the stacked barplot image you are redirected to the grouped barplot page, and the same happens for the grouped barplot image, but it redirects you to the stacked barplot page.

Thanks for your amazing work.

Kind regards,

Ricard

**Comment by Didayolo** [comment]
I was going to report this :+1:

**Comment by holtzy** [comment]
Fixed. Thanks so much 🙏 !
