### ISSUE TITLE
Add time spirals?

### ISSUE THREAD

**Issue by AllanLRH** [holtzy/The-Python-Graph-Gallery#7]
Time spirals are cool! You should consider adding them to the site (which I BTW really like).
<img width="811" alt="screen shot 2018-08-24 at 16 08 55" src="https://user-images.githubusercontent.com/2641327/44589159-113f9200-a7b8-11e8-9959-bbce082d77c9.png">

[Source](http://stat-computing.org/newsletter/issues/scgn-22-1.pdf) (PDF, page 6)

**Comment by holtzy** [comment]
Why not! Do you have any reproducible code to share?
