### ISSUE TITLE
Bug circular packing?

### ISSUE THREAD

**Issue by holtzy** [holtzy/The-Python-Graph-Gallery#74]
I came across your document on the web regarding the Basic Circle Packing Chart. You stated that the second column (Value) of the dataframe will control the bubble size. But from the chart created, it seems like the value didn’t control the size cause D is way smaller than F and the other circles are not scaled proportionately. May I know how do i make the size of the bubbles based on the value?

**Comment by sunefibaek** [comment]
The solution is to reverse the order of the data with: circles = circles[::-1]
See https://github.com/holtzy/The-Python-Graph-Gallery/pull/258 for details.

**Comment by holtzy** [comment]
Fixed!
