### ISSUE TITLE
Get rid of jet

### ISSUE THREAD

**Issue by flying-sheep** [holtzy/The-Python-Graph-Gallery#8]
Jet is bad, so it shouldn’t prominently appear in the gallery (e.g. [here](https://python-graph-gallery.com/2d-density-plot/)). The new default viridis should step in nicely.

**Comment by holtzy** [comment]
Jet is not that bad in this particular case. Even though I agree it is bad in many cases. I believe the examples can remain that way for now.
Thanks for the feedback, I gonna add some explanation on why jet is bad somewhere.

**Comment by flying-sheep** [comment]
Why do you think it’s not bad in this case? It’s a histogram, so color encodes density, which means that using Jet here creates artifacts and is therefore a bad choice.
