### ISSUE TITLE
venn background color example broken

### ISSUE THREAD

**Issue by EricThomson** [holtzy/The-Python-Graph-Gallery#9]
In reference to:
https://python-graph-gallery.com/174-change-background-colour-of-venn-diagram/

Following line uses deprecated feature and throws an error:
`plt.gca().set_axis_bgcolor('skyblue')`

The following works:
`    plt.gca().set_facecolor('skyblue')`

**Comment by holtzy** [comment]
Done in new version coming soon. Thanks for the feedback!
